- platform: template
  sensors:
    irrigation_weather_outlook:
      friendly_name: "Irrigation weather outlook"
      value_template: "{{ state_attr('sensor.current_weather_owm', 'temp') }}"

- platform: template
  sensors:
    temp_woonk_vloerv:
      friendly_name: "Woonk. Vloerv."
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.controller', 'current_temperature') }}"

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"

- platform: template
  sensors:
    smartphone_kim_battery_level:
      value_template: '{{ state_attr("device_tracker.google_maps_115305887383945385383", "battery_level")}}'

- platform: template
  sensors:
    smartphone_max_battery_level:
      value_template: '{{ state_attr("device_tracker.google_maps_104742499472119555757", "battery_level")}}'

- platform: template
  sensors:
    smartphone_jelica_battery_level:
      value_template: '{{ state_attr("device_tracker.google_maps_110946189396379150601", "battery_level")}}'

- platform: template
  sensors:
    solaredge_lifetime_energy_kwh:
      friendly_name: "Solar Lifetime kwh"
      unit_of_measurement: "kWh"
      value_template: "{{ states('sensor.solaredge_lifetime_energy') | float / 1000 }}"

- platform: template
  sensors:
    current_humidity:
      value_template: '{{ state_attr("humidifier.humidifier", "current_humidity")}}'
      friendly_name: Current Humidity
      attribute_templates:
        humidity: '{{ state_attr("humidifier.humidifier", "current_humidity")}}'

- platform: template
  sensors:
    current_power_consumption:
      friendly_name: "Energie Verbruik (totaal)"
      unit_of_measurement: "W"
      value_template: '{{ states("sensor.solaredge_current_power") |float + states("sensor.p1_meter_3c39e727c82a_active_power") | float }}'

- platform: template
  sensors:
    afval_vandaag:
      value_template: >-
        {% set afvalsoort = states('sensor.afvalwijzer_today') %}
        {% if afvalsoort == "gft" %}GFT
        {% elif afvalsoort == "plastic" %}PMD
        {% elif afvalsoort == "papier" %}Papier
        {% else %}Geen
        {%- endif %}
      entity_picture_template: >-
        {% set afvalsoort = states('sensor.afvalwijzer_today') %}
        {% if afvalsoort == "gft" %}/local/mijnafvalwijzer/gft3.png
        {% elif afvalsoort == "plastic" %}/local/mijnafvalwijzer/plastic3.png
        {% elif afvalsoort == "papier" %}/local/mijnafvalwijzer/papier3.png
        {% else %}
        {%- endif %}
    afval_morgen:
      value_template: >-
        {% set afvalsoort = states('sensor.afvalwijzer_tomorrow') %}
        {% if afvalsoort == "gft" %}GFT
        {% elif afvalsoort == "plastic" %}PMD
        {% elif afvalsoort == "papier" %}Papier
        {% else %}Geen
        {%- endif %}
      entity_picture_template: >-
        {% set afvalsoort = states('sensor.afvalwijzer_tomorrow') %}
        {% if afvalsoort == "gft" %}/local/mijnafvalwijzer/gft3.png
        {% elif afvalsoort == "plastic" %}/local/mijnafvalwijzer/plastic3.png
        {% elif afvalsoort == "papier" %}/local/mijnafvalwijzer/papier3.png
        {% else %}
        {%- endif %}
    afval_overmorgen:
      value_template: >-
        {% set afvalsoort = states('sensor.afvalwijzer_day_after_tomorrow') %}
        {% if afvalsoort == "gft" %}GFT
        {% elif afvalsoort == "plastic" %}PMD
        {% elif afvalsoort == "papier" %}Papier
        {% else %}Geen
        {%- endif %}
      entity_picture_template: >-
        {% set afvalsoort = states('sensor.afvalwijzer_day_after_tomorrow') %}
        {% if afvalsoort == "gft" %}/local/mijnafvalwijzer/gft3.png
        {% elif afvalsoort == "plastic" %}/local/mijnafvalwijzer/plastic3.png
        {% elif afvalsoort == "papier" %}/local/mijnafvalwijzer/papier3.png
        {% else %}
        {%- endif %}
