###############################################
## Home-Assistant
################################################
homeassistant:
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks: 
        !secret homeassistant.trusted_networks
  customize: !include customize.yaml
  customize_glob: !include configuration/customize_glob/customize_glob.yaml


http:
  server_port: !secret http.server_port
  base_url: !secret http.base_url
  ssl_certificate: !secret http.ssl_certificate
  ssl_key: !secret http.ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 5 

lovelace:
  mode: storage
  dashboards: !include configuration/dashboards/dashboards.yaml
 

camera: !include configuration/cameras/cameras.yaml
group: !include_dir_merge_named configuration/groups/
history: !include configuration/logging/history.yaml
light: !include configuration/lights/lights.yaml
logbook: !include configuration/logging/logbook.yaml
logger: !include configuration/logging/logger.yaml
recorder: !include configuration/logging/recorder.yaml
sensor: !include configuration/sensors/sensors.yaml
switch: !include configuration/switches/switches.yaml
variable: !include configuration/variables/variables.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml


frontend:
#  themes: !include_dir_merge_named themes

browser_mod:
config:
discovery:
ffmpeg:
lovelace_gen:
map:
mobile_app:
person:
stream:  
sun:
system_health:
#webhook:

alarm_control_panel:
  - platform: manual  

input_boolean:
  vacation_mode:
#    initial: off

webostv:
  host: !secret webostv_ip
  name: Woonkamer TV
  turn_on_action:
    service: persistent_notification.create
    data:
      message: "Turn on action"
  customize:
    sources:
      - livetv
      - decoder
      - thuisbioscoop
      - gameconsole

 




