#security
- platform: template
  sensors:
    woonkamer_motion_meta:
      friendly_name: 'Woonkamer'
      device_class: motion
      value_template: >-
        {%- if is_state("binary_sensor.pir_woonkamer_home_security_motion_detection", "on")
        or is_state("binary_sensor.motion_sensor_woonkamer", "on")
        -%}
        True
        {%- else -%}
        False
        {%- endif %}