# cameras

- platform: ffmpeg
  name: Begane Grond
  input: !secret camera_begane_grond.input

- platform: ffmpeg
  name: Begane Grond 2
  input: !secret camera_begane_grond2.input

#- platform: ffmpeg
#  name: Achtertuin
#  input: !secret camera_achtertuin.input

- platform: ffmpeg
  name: Straatzijde
  input: !secret camera_straatzijde.input

#- platform: synology
#  url: https://treecentral.vandenboom.org:5001
#  username: admin
#  password: 3Vdb8458
#  verify_ssl: false

- platform: proxy
  entity_id: camera.voordeur_mediaprofile_channel1_mainstream
  name: camera.voordeur_resized
  mode: resize
  max_stream_width: 360
