- platform: proxy
  entity_id: camera.achtertuin_schuifpui
  name: Achtertuin ProxyCam
  max_stream_width: 360
  max_image_width: 720

- platform: proxy
  entity_id: camera.begane_grond_pt
  name: Begane Grond ProxyCam
  max_stream_width: 360
  max_image_width: 720

- platform: proxy
  entity_id: camera.woonkamer1
  name: Begane Grond 2 ProxyCam
  max_stream_width: 360
  max_image_width: 720

- platform: proxy
  entity_id: camera.voordeur
  name: Voordeur ProxyCam
  max_stream_width: 360
  max_image_width: 720

- platform: proxy
  entity_id: camera.straatijde
  name: Straatzijde ProxyCam
  max_stream_width: 360
  max_image_width: 720

- platform: proxy
  entity_id: camera.achtertuin_schuur
  name: Achteruin Schuur ProxyCam
  max_stream_width: 360
  max_image_width: 720

