#security

binary_sensor:
  - platform: template
    sensors:
      woonkamer_motion_meta:
        friendly_name: 'Woonkamer'
        device_class: motion
        value_template: >-
          {%- if is_state("binary_sensor.kaipule_technology_co_ltd_pir_celling_sensor_sensor_2", "on")
          or is_state("binary_sensor.motion_sensor", "on")
          -%}
          True
          {%- else -%}
          False
          {%- endif %}