################################################
## Packages / Trash
################################################
homeassistant:
  customize:
    sensor.afvalwijzer_today:
      friendly_name: Vandaag
    sensor.afvalwijzer_tomorrow:
      friendly_name: Morgen
    sensor.afvalwijzer_next_in_days:
      friendly_name: Next pickup in days
#    group.trash_pickup:
#     icon: mdi:trash-can

    sensor.afvalwijzer_gft:
      friendly_name: GFT
      entity_picture: /local/mijnafvalwijzer/gft3.png
    sensor.afvalwijzer_papier:
      friendly_name: Papier
      entity_picture: /local/mijnafvalwijzer/papier3.png
    sensor.afvalwijzer_plastic:
      friendly_name: PMD
      entity_picture: /local/mijnafvalwijzer/plastic3.png
    sensor.afvalwijzer_restafval:
      friendly_name: Restafval
      entity_picture: /local/mijnafvalwijzer/rest3.png

    sensor.afvalwijzer_gft_formatted:
      entity_picture: /local/mijnafvalwijzer/gft3.png
    sensor.afvalwijzer_papier_formatted:
      entity_picture: /local/mijnafvalwijzer/papier3.png
    sensor.afvalwijzer_plastic_formatted:
      entity_picture: /local/mijnafvalwijzer/plastic3.png
    sensor.afvalwijzer_restafval_formatted:
      entity_picture: /local/mijnafvalwijzer/rest3.png
    

################################################
## Input Boolean
################################################
#input_boolean:
#  waste_moved:
#    name: Waste has been moved
#    initial: 'off'
#    icon: mdi:delete-empty
#  waste_reminder:
#    name: Waste reminder enabled
#    initial: 'on'

################################################
## Sensor
################################################
sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer or afvalstoffendienstkalender
    postal_code: '4823MG'              # (required, default = '')
    street_number: '41'               # (required, default = '')
    suffix: ''                         # (optional, default = '')
    include_date_today: false        # (optional, default = false) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found


################################################
## Automation
################################################
automation:
#  - alias: Reset waste notification
#    trigger:
#      platform: state
#      entity_id: input_boolean.waste_moved
#      to: 'on'
#      for:
#        hours: 12
#    action:
#      - service: input_boolean.turn_off
#        entity_id: input_boolean.waste_moved
#      - service: input_boolean.turn_on
#        entity_id: input_boolean.waste_reminder

#  - alias: Mark waste as moved from notification
#    trigger:
#      platform: event
#      event_type: ios.notification_action_fired
#      event_data:
#        actionName: MARK_WASTE_MOVED
#    action:
#      - service: input_boolean.turn_on
#        entity_id: input_boolean.waste_moved

#  - alias: Waste has not been moved
#    trigger:
#      platform: time_pattern
#      hours: 1
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: input_boolean.waste_moved
#          state: 'off'
#        - condition: state
#          entity_id: input_boolean.waste_reminder
#          state: 'on'
#        - condition: time
#          after: '18:00:00'
#          before: '23:00:00'
#        - condition: template
#          value_template: "{{ states('sensor.afvalwijzer_tomorrow') != 'Geen' }}"
#    action:
#      - service: notify.family
#        data:
#          title: "Afval"
#          message: 'Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. Afvaltype(n): {{ states.sensor.afvalwijzer_tomorrow.state }} wordt opgehaald op: {{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%d-%m-%Y", True) }}!'
#          data:
#            push:
#              badge: 0
#              category: 'afval'